;;;; tracker.lisp — the issue tracker, end to end

(in-package #:littoral/tests)

(def-suite tracker :in littoral)
(in-suite tracker)

(defmacro with-tracker ((&key file) &body body)
  "Run BODY with an empty tracker served at /tracker, saving to FILE if given."
  `(let ((littoral-tracker:*tracker-file* ,file))
     (littoral-tracker:reset-tracker)
     (with-fresh-applications (("/tracker" 'littoral-tracker:tracker :mode :deployment))
       ,@body)))

(defun register-user (b name &optional (password "correct horse"))
  "Create an account called NAME and log in."
  (visit b "/tracker")
  (click b "create an account")
  (fill-in b "name" name)
  (fill-in b "email" (format nil "~A@example.org" name))
  (fill-in b "password" password)
  (fill-in b "confirm" password)
  (press b "Create account"))

(defun log-in-as (b name &optional (password "correct horse"))
  "Log in to the tracker as NAME."
  (visit b "/tracker")
  (click b "Log in")
  (fill-in b "username" name)
  (fill-in b "password" password)
  (press b "Log in"))

(defun file-issue (b title &key (priority "Normal") body)
  "File an issue called TITLE from the issue list."
  (click b "New issue")
  (fill-in b "title" title)
  (when body (fill-in b "body" body))
  (select-option b "priority" priority)
  (press b "File issue"))

(test registration-and-login
  (with-tracker ()
    (let ((b (make-instance 'browser)))
      (visit b "/tracker")
      (click b "create an account")
      (fill-in b "name" "ada")
      (fill-in b "email" "ada@example.org")
      (fill-in b "password" "short")
      (fill-in b "confirm" "different")
      (press b "Create account")
      (is (has-text-p b "at least 8 characters"))
      (fill-in b "password" "long enough")
      (fill-in b "confirm" "not the same")
      (press b "Create account")
      (is (has-text-p b "The passwords differ."))
      (fill-in b "password" "long enough")
      (fill-in b "confirm" "long enough")
      (press b "Create account")
      (is (has-text-p b "ada · Log out"))
      (is (has-text-p b "No issues here.")))
    ;; Logging in, wrongly then rightly; names are taken once.
    (let ((b (make-instance 'browser)))
      (log-in-as b "ada" "wrong password")
      (is (has-text-p b "Unknown user or wrong password."))
      (fill-in b "username" "ADA")
      (fill-in b "password" "long enough")
      (press b "Log in")
      (is (has-text-p b "ada · Log out"))
      (click b "Log out")
      (is (has-text-p b "An issue tracker built with Littoral.")))
    (let ((b (make-instance 'browser)))
      (register-user b "ada")
      (is (has-text-p b "That name is taken.")))))

(test issues-lifecycle
  (with-tracker ()
    (let ((ada (make-instance 'browser)))
      (register-user ada "ada")
      (click ada "New issue")
      (press ada "File issue")
      (is (has-text-p ada "Title is required."))
      (press ada "Cancel")
      (file-issue ada "Pages render slowly" :priority "High" :body (format nil "Very slowly.~%Sometimes."))
      (is (has-text-p ada "#1 Pages render slowly"))
      (is (has-text-p ada "high priority · reported by ada"))
      (is (search "Very slowly.<br>Sometimes." (browser-html ada)))
      ;; Work on it.
      (click ada "Assign to me")
      (is (has-text-p ada "assigned to ada"))
      (click ada "Start work")
      (is (has-text-p ada "In Progress"))
      (fill-in ada "comment" "Found it: the snapshot is huge.")
      (press ada "Comment")
      (is (has-text-p ada "1 comment"))
      (is (has-text-p ada "Found it: the snapshot is huge."))
      ;; Edit through a draft.
      (click ada "Edit")
      (fill-in ada "title" "Pages render slowly on big lists")
      (fill-in ada "due" "2026-12-31")
      (press ada "Save")
      (is (has-text-p ada "#1 Pages render slowly on big lists"))
      (is (has-text-p ada "due 2026-12-31"))
      ;; Cancelling an edit changes nothing.
      (click ada "Edit")
      (fill-in ada "title" "Something else")
      (press ada "Cancel")
      (is (has-text-p ada "#1 Pages render slowly on big lists"))
      (click ada "Close")
      (is (has-text-p ada "Reopen"))
      (click ada "All issues")
      (is (has-text-p ada "Open (0)"))
      (is (has-text-p ada "Closed (1)")))))

(test filters-search-and-sharing
  (with-tracker ()
    (let ((ada (make-instance 'browser)) (bob (make-instance 'browser)))
      (register-user ada "ada")
      (register-user bob "bob")
      (file-issue ada "Login page typo")
      (click ada "All issues")
      (file-issue ada "Crash on empty cart" :priority "Urgent")
      (click ada "All issues")
      ;; Bob sees Ada's issues.
      (visit bob (browser-url bob))
      (is (has-text-p bob "Login page typo"))
      (is (has-text-p bob "Crash on empty cart"))
      (is (search "class=\"urgent\"" (browser-html bob)))
      ;; Search, by AJAX.
      (let* ((spec (first (ajax-specs bob "on-input")))
             (json (ajax-request bob (first spec) (rest spec)
                                 :fields (list (cons (element-name bob "query") "crash")))))
        (is (search "Crash on empty cart" json))
        (is (not (search "Login page typo" json))))
      ;; Assigned to me.
      (visit bob (browser-url bob))
      (click bob "Crash on empty cart")
      (click bob "Assign to me")
      (click bob "All issues")
      (click bob "Assigned to me")
      (is (has-text-p bob "Crash on empty cart"))
      (is (not (has-text-p bob "Login page typo"))))))

(test live-updates-reach-other-users
  (with-tracker ()
    (let ((ada (make-instance 'browser)) (bob (make-instance 'browser)) (sink (make-instance 'sink)))
      (register-user ada "ada")
      (register-user bob "bob")
      (let ((stream (open-stream bob sink)))
        (is (wait-for (lambda () (search "retry:" (sink-text sink)))))
        (file-issue ada "Filed while Bob watches")
        (is (wait-for (lambda () (search "Filed while Bob watches" (sink-text sink)))))
        (close-event-streams)
        (is (wait-for (lambda () (not (sb-thread:thread-alive-p stream)))))))))

(test data-survives-a-restart
  (let ((file (format nil "/tmp/littoral-tracker-~D.lisp" (random 1000000))))
    (unwind-protect
         (progn
           (with-tracker (:file file)
             (let ((ada (make-instance 'browser)))
               (register-user ada "ada")
               (file-issue ada "Remember me" :body "Across restarts.")
               (fill-in ada "comment" "Still here?")
               (press ada "Comment")))
           (is (= #o600 (logand #o777 (sb-posix:stat-mode (sb-posix:stat file)))))
           ;; A new process, as far as the store can tell.
           (littoral-tracker:reset-tracker)
           (littoral-tracker::load-store file)
           (with-fresh-applications (("/tracker" 'littoral-tracker:tracker :mode :deployment))
             (let ((ada (make-instance 'browser)))
               (log-in-as ada "ada")
               (is (has-text-p ada "Remember me"))
               (click ada "Remember me")
               (is (has-text-p ada "Across restarts."))
               (is (has-text-p ada "Still here?")))))
      (ignore-errors (delete-file file))
      (littoral-tracker:reset-tracker))))

(test bookmarked-issue-opens-after-signing-in
  (with-tracker ()
    (let ((ada (make-instance 'browser)))
      (register-user ada "ada")
      (file-issue ada "Bookmark this")
      (is (search "/tracker/issue/1?" (browser-url ada)))
      (let ((bob (make-instance 'browser)))
        (register-user bob "bob")
        (let ((reader (make-instance 'browser)))
          (visit reader "/tracker/issue/1")
          (click reader "Log in")
          (fill-in reader "username" "bob")
          (fill-in reader "password" "correct horse")
          (press reader "Log in")
          (is (has-text-p reader "#1 Bookmark this")))))))
